# Generated by Django 3.2.8 on 2021-11-02 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('def_street_address', models.CharField(blank=True, max_length=80, null=True)),
                ('def_town_or_city', models.CharField(blank=True, max_length=60, null=True)),
                ('def_county', models.CharField(blank=True, max_length=60, null=True)),
                ('def_postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('def_country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
